hostelfinder/hostelAdmin/urls.py
from . import views
from django.conf.urls import url

app_name = 'hostelAdmin'

urlpatterns = [
    url(r'^$', views.HostelView, name='hostels'),
    url(r'^hostels/$', views.HostelView, name='hostels'),
    url(r'^hostels/(?P<pk>[0-9]+)/$', views.HostelDetailView, name='hostel_details'),
    url(r'^hostels/edit/(?P<pk>[0-9]+)/$', views.HostelEditView, name='hostel_edit'),
    url(r'^hostels/delete/(?P<pk>[0-9]+)/$', views.HostelDeleteView, name='hostel_delete'),
    url(r'^hostels/add/$', views.formHostel, name='hostel_add'),
    url(r'^customers/$', views.customers, name='customers')
]

hostelfinder/hostelfinder/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hostelAdmin/', include('hostelAdmin.urls')),
    url(r'^hostelfinder/', include('webpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hostelfinder/webpage/urls.py
from . import views
from django.conf.urls import url

app_name = 'webpage'

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^hostels/(?P<pk>[0-9]+)/$', views.HostelDetailView, name='hostel_details'),
    url(r'^hostels/edit/(?P<pk>[0-9]+)/$', views.HostelEditView, name='hostel_edit'),
    url(r'^hostel/(?P<pk>[0-9]+)/rate/(?P<rate>[1-5]+)/$', views.rating, name='rate'),
    url(r'^register_form/(?P<user_type>[a-zA-Z_]+)/$', views.register_form_view, name='register_form'),
    url(r'^login/', views.login_form_view, name='login'),
    url(r'^logout/', views.log_out, name='logout'),
    url(r'^search_bar/', views.search_bar, name='search_bar'),
    url(r'^user_page/hostel_owner/(?P<user_id>[0-9]+)/$', views.user_hostel_owner, name='user_hostel_owner'),
    url(r'^user_page/student/(?P<user_id>[0-9]+)/$', views.user_student, name='user_student'),
]

hostelfinder/hostelAdmin/models.py
from django.db import models
from django.urls import reverse

class Location(models.Model):
    district = models.CharField(max_length=250, default="Kathmandu")
    street = models.CharField(max_length=250)
    province = models.IntegerField(default=3)
    zip = models.CharField(max_length=250, default="44600")
    country = models.CharField(max_length=250, default="Nepal")

    def __str__(self):
        return self.street + ' - ' + self.district

class Hostel(models.Model):
    HOSTEL_CHOICE = {
        ('B','Boys Hostel'),
        ('G', 'Girls Hostel'),
    }
    hostel_name =  models.CharField(max_length=250)
    hostel_type =  models.CharField(max_length=20, choices=HOSTEL_CHOICE)
    hostel_phone =  models.CharField(max_length=100, null = True, blank=True)
    hostel_mobile = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default=1)
    latitude = models.DecimalField(max_digits=10,decimal_places=8, default=0.000000)
    longitude = models.DecimalField(max_digits=11,decimal_places=8, default=0.00000)
    additional_location = models.CharField(max_length=250, null = True, blank=True)

    #def get_absolute_url(self):
     #   return reverse('hostelAdmin:hostel_details', kwargs={'pk':self.pk})

    def __str__(self):
        return str(self.pk)+' - '+self.hostel_name + '('+  self.hostel_type +')'


class Room(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    seater_type= models.IntegerField(default=1)
    quantity = models.IntegerField(default=1)
    room_price = models.CharField(max_length=250)
    available = models.IntegerField(default=0)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' - room'+  str(self.quantity)

class Fee(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    admission_fee = models.IntegerField(default=0)
    refundable_fee = models.IntegerField(default=0)
    security_fee = models.IntegerField(default=0)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' fee'

class Image(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    profile_image = models.FileField(null=True,blank=True)
    hostel_image = models.FileField(null=True,blank=True)
    kitchen = models.FileField(null=True,blank=True)
    room = models.FileField(null=True,blank=True)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' images'

hostelfinder/hostelAdmin/forms.py
from django.forms import  ModelForm
from django import forms
from hostelAdmin.models import Hostel, Room, Fee,Image

class HostelForm(ModelForm):
    class Meta:
        model=Hostel
        fields = ['hostel_name','hostel_type','hostel_phone','hostel_mobile','location','latitude','longitude','additional_location']
        widgets = {
            'hostel_name': forms.TextInput(attrs={'style': 'width:100%;'}),
            'hostel_type': forms.Select(attrs={'style': 'width:150px'}),
            'hostel_phone': forms.TextInput(attrs={'style': 'width:200px'}),
            'hostel_mobile': forms.TextInput(attrs={'style': 'width:200px'}),
            'location': forms.Select(attrs={'style': 'width:350px'}),
            'latitude': forms.TextInput(attrs={'style': 'width:150px'}),
            'longitude': forms.TextInput(attrs={'style': 'width:150px'}),
            'additional_location': forms.TextInput(attrs={'style': 'width:250px'}),
        }

class RoomForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(RoomForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['room_price'].required = False

    class Meta:
        model = Room
        fields = ['seater_type','quantity','room_price','available']
        widgets = {
            'seater_type': forms.NumberInput(attrs={'id': 'seater_type'}),
            'quantity': forms.NumberInput(attrs={'id': 'quantity'}),
            'room_price': forms.TextInput(attrs={'id': 'room_price'}),
            'available': forms.NumberInput(attrs={'id': 'available'}),
        }

class FeeForm(ModelForm):
    class Meta:
        model = Fee
        fields = ['admission_fee','refundable_fee','security_fee']

class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['profile_image','hostel_image','room','kitchen']


class RoomDetailForm(forms.Form):
        room_detail = forms.CharField(label='',required=False,widget=forms.Textarea(attrs={'id': 'room_json','style':'display:none;'}))
        class Meta:
            fields = ['room_detail']

hostelfinder/hostelAdmin/views.py
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from django.views import generic
from .models import Hostel, Location, Room, Fee, Image
from .forms import HostelForm, RoomForm, FeeForm, RoomDetailForm, ImageForm
from django.contrib import messages
import json

def HostelView(request):
    hostel_list = Hostel.objects.all()
    location = Location.objects.all()

    paginator = Paginator(hostel_list, 10)  # Show 10 contacts per page

    page = request.GET.get('page')
    hostel = paginator.get_page(page)
    return render(request, 'hostelAdmin/hostels.html', {'hostels': hostel, 'locations':location})

def HostelDetailView(request, pk):
    hostel = Hostel.objects.get(id=pk)
    args = {'hostel':hostel}
    return render(request,'hostelAdmin/hostel_detail.html',args)


def HostelEditView(request, pk):
    if request.method == "POST":
        hostel_form = HostelForm(request.POST,instance=Hostel.objects.get(id=pk))
        room_form = RoomForm(request.POST)
        fee_form = FeeForm(request.POST,instance=Fee.objects.get(hostel_id=pk))
        roomDetail_form = RoomDetailForm(request.POST)
        image_form = ImageForm(request.POST,request.FILES,instance=Image.objects.get(hostel_id=pk))
        data = roomDetail_form.data['room_detail']

        if hostel_form.is_valid() and fee_form.is_valid() and image_form.is_valid():
            hostel = hostel_form.save()
            room = room_form.save(False)
            fee = fee_form.save(False)
            image = image_form.save(False)

            Room.objects.filter(hostel_id=pk).delete()

            if data:
                data = json.loads(roomDetail_form.data['room_detail'])

                for x in data:
                    r = Room()
                    r.hostel = hostel
                    r.seater_type = x['seater_type']
                    r.quantity = x['quantity']
                    r.room_price = x['room_price']
                    r.available=x['available']
                    r.save()

            room.hostel =hostel
            fee.hostel = hostel
            image.hostel = hostel
            fee.save()
            image.save()

            return redirect("hostelAdmin:hostel_details",pk=pk)

    else:
        hostel_form = HostelForm(instance=Hostel.objects.get(id=pk))
        room_form = RoomForm()

        #for fill the list in the room_detail field in RoomDetailForm
        room = list(Room.objects.filter(hostel_id=pk))
        room_detail = []

        for x in room:
            room_detail.append({
                'seater_type':x.seater_type,
                'quantity':x.seater_type,
                'room_price':x.room_price,
                'available':x.available
            })

        roomDetail_form = RoomDetailForm(initial={'room_detail': json.dumps(room_detail)})
        fee_form = FeeForm(instance=Fee.objects.get(hostel_id=pk))
        image_form = ImageForm(instance=Image.objects.get(hostel_id=pk))

    args = {}
    #args.update(csrf(request))
    args['hostel_form'] = hostel_form
    args['room_form'] = room_form
    args['fee_form'] = fee_form
    args['roomDetail_form'] = roomDetail_form
    args['image_form'] = image_form
    args['hostel'] = Hostel.objects.get(id=pk)

    return render(request,'hostelAdmin/hostel_edit.html',args)


#class HostelCreate(generic.CreateView):
 #  model = Hostel
 #  fields = ['hostel_name','hostel_type','hostel_phone','hostel_mobile']

def formHostel(request):
    if request.method == "POST":
        hostel_form = HostelForm(request.POST)
        room_form = RoomForm(request.POST)
        fee_form = FeeForm(request.POST)
        image_form = ImageForm(request.POST,request.FILES)
        roomDetail_form = RoomDetailForm(request.POST)
        data = roomDetail_form.data['room_detail']

        if hostel_form.is_valid() and fee_form.is_valid() and image_form.is_valid():
            hostel = hostel_form.save()
            room = room_form.save(False)
            fee = fee_form.save(False)
            image = image_form.save(False)

            if data:
                data = json.loads(roomDetail_form.data['room_detail'])
                print(data)

                for x in data:
                   r = Room()
                   r.hostel=hostel
                   r.seater_type=x['seater_type']
                   r.quantity=x['quantity']
                   r.room_price=x['room_price']
                   r.available=x['available']
                   r.save()

            room.hostel =hostel
            fee.hostel = hostel
            image.hostel = hostel
            fee.save()
            image.save()

            return redirect("hostelAdmin:hostels")

    else:
        hostel_form = HostelForm()
        room_form = RoomForm()
        fee_form = FeeForm()
        roomDetail_form = RoomDetailForm()
        image_form = ImageForm()

    args = {}
    #args.update(csrf(request))
    args['hostel_form'] = hostel_form
    args['room_form'] = room_form
    args['fee_form'] = fee_form
    args['roomDetail_form'] = roomDetail_form
    args['image_form'] = image_form

    return render(request,'hostelAdmin/new_hostel.html',args)

def HostelDeleteView(request,pk):
    hostel = get_object_or_404(Hostel, id=pk)
    try:
        if request.method == "POST" and request.user.is_authenticated:
            print("fa")
            hostel.delete()
            messages.success(request, "Post successfully deleted!")
            return redirect("hostelAdmin:hostels")
    except Exception as e:
        messages.warning(request,"could not delete: Error {}".format(e))

    args = {'hostel': hostel}

    return render(request,'hostelAdmin/hostel_detail.html',args)

def customers(request):
    return render(request,'hostelAdmin/customers.html')

hostelfinder/hostelAdmin/templates/hostelAdmin/Hostel_form.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}

{% block body %}
<div clas="row"></div>
    <div class="container" style="margin-top: 80px;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'hostelAdmin/form-template.html' %}
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit">Submit</button>
                    </div>
                </div>
        </form>
    </div>
{% endblock %}

hostelfinder/hostelAdmin/templates/hostelAdmin/customers.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-customers %}class="nav-link active"{% endblock %}

{% block body %}
    <div class="container">
        <p>customers</p>
    </div>
{% endblock %}

hostelfinder/hostelAdmin/templates/hostelAdmin/form-template.html
{% for field in form %}
    <div class="col-sm-10 col-sm-offset-2">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10 col-sm-offset-2"> {{ field }} </div>
{% endfor %}

hostelfinder/hostelAdmin/templates/hostelAdmin/hostel_detail.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}

{% block body %}
<div clas="row"></div>

    {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'hostel_delete' %}
            <div class="container">
                <h1>Delete {{ hostel.hostel_name }}?</h1>

                <form method="POST" action="{% url 'hostelAdmin:hostel_delete' hostel.pk %}">
                {% csrf_token %}
                Are you sure you want to delete this post?
                <input type="submit" value="Yes"/>
                <a href="{% url 'hostelAdmin:hostel_details' hostel.pk %}">Cancel</a>
                </form>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container" style="margin-top: 80px;">

        <h1>hostel</h1>
        <p>{{ hostel.hostel_name }}</p>
        <p>{{ hostel.hostel_type }}</p>
        <p>{{ hostel.hostel_phone }}</p>
        <p>{{ hostel.hostel_mobile }}</p>

        <h2>location</h2>
        <p>{{ hostel.location }}</p>
        <p>{{ hostel.latitude }}</p>
        <p>{{ hostel.longitude }}</p>
        <p>{{ hostel.additional }}</p>

        <h2>room detail</h2>
        {% for room in hostel.room_set.all %}
            <p>{{ room.seater_type }}-{{ room.quantity }}-{{room.room_price}}</p>
        {% endfor %}

        <h2>fee detail</h2>
        {% for fee in hostel.fee_set.all %}
            <p>{{ fee.admission_fee }}-{{fee.refundable_fee}}-{{ fee.security_fee }}</p>
        {% endfor %}

        <h2>image detail</h2>
        {% for image in hostel.image_set.all %}
            <p style="float:left;"><label>profile image</label><img src="/media/{{ image.profile_image }}" height="200px" width="200px"/></p>
             <p><label>image 1</label><img src="/media/{{ image.image1 }}" height="200px" width="200px" alt="no image"/></p>
             <p><label>image 2</label><img src="/media/{{ image.image2 }}" height="200px" width="200px" alt="no image"/></p>
             <p><label>image 3</label><img src="/media/{{ image.image3 }}" height="200px" width="200px" alt="no image"/></p>
             <p><label>image 4</label><img src="/media/{{ image.image4 }}" height="200px" width="200px" alt="no image"/></p>
             <p><label>image 5</label><img src="/media/{{ image.image5 }}" height="200px" width="200px" alt="no image"/></p>
        {% endfor %}

        <a href="{% url 'hostelAdmin:hostel_edit' hostel.pk %}">
            <button type="button" class="btn btn-info"><i class="far fa-edit"></i>Edit</button>
        </a>
        <a href="{% url 'hostelAdmin:hostel_delete' hostel.pk %}">
            <button type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</button>
        </a>
    </div>
{% endblock %}

hostelfinder/hostelAdmin/templates/hostelAdmin/hostel_edit.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}
{% load bootstrap4 %}

{% block body %}
 <div class="container" style="margin-top: 60px; margin-bottom: 60px; background-color:white; border-radius:4px; padding:20px; display:flex;">
        <form method="POST" class="form" enctype="multipart/form-data" action="{% url 'hostelAdmin:hostel_edit' hostel.pk %}">
            {% csrf_token %}
            {% bootstrap_form hostel_form %}
            <hr>
            {% bootstrap_form fee_form %}
            <hr>
            {% bootstrap_form room_form %}
            <div class="form-group">
                <label style="visibility:hidden">add button</label>
                    <div class="col-sm-5">
                        <button type="button" class="btn btn-info" id="add">Add</button>
                    </div>
            </div>
            <div id="room_error"></div>
            <div id="room">
                <table class="table">
                    <thead>
                        <th>Seater Type</th>
                        <th>Quantity</th>
                        <th>Room Price</th>
                        <th>Available</th>
                    </thead>
                    <tbody id="room_table">

                    </tbody>
                </table>
            </div>
            {% bootstrap_form roomDetail_form %}
            <hr>
            {% bootstrap_form image_form %}
            <hr>
            <div class="form-group" style="clear:both; position:relative; left:45%; top:10px;">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
       <script>
        var arr = [];

        window.onload = function(){
                room_detail = $('#room_json').val();
                arr = JSON.parse(room_detail);
                createTable(arr);
        }

        function createJSON(seater_type,quantity,room_price,available){
            arr.push({
                "seater_type" : seater_type,
                "quantity" : quantity,
                "room_price" : room_price,
                "available" : available,
            });

            return arr;
        }

        function createTable(data){
            var room = '';
            var room_json = [];

            for(value in data){
                 room += '<tr id="room'+ value +'">';
                 room += '<td>'+data[value].seater_type+'</td>';
                 room += '<td>'+data[value].quantity+'</td>';
                 room += '<td>'+data[value].room_price+'</td>';
                 room += '<td>'+data[value].available+
                  '<button type="button" class="btn btn-danger"  style="margin-left:50px;"><i class="fas fa-trash-alt"></i></button></td>';
                 room += '</tr>';
            }

            $('#room_table').html(room);

            for(value in arr){
                room_json.push({
                    "seater_type" : arr[value].seater_type,
                    "quantity" : arr[value].quantity,
                    "room_price" : arr[value].room_price,
                    "available" : arr[value].available,
                });
            }

            $('#room_json').val(JSON.stringify(room_json));
        }

            $('#add').click(function(){

                seater_type = $('#seater_type').val();
                quantity = $('#quantity').val();
                room_price = $('#room_price').val();
                available = $('#available').val();

                if(valid()){
                    createJSON(seater_type,quantity,room_price,available);
                    console.log(arr);
                    createTable(arr);
                    $('#room_price').val("");
                }

                function valid(){
                    if(room_price == "" || seater_type == 0 || quantity == 0){
                        $('#room_error').html("<p style='color:red;'>please! insert the values.....<p>");

                        if(room_price=="")
                        $('#room_error').append("<p style='color:red;'>* room price required</p>");

                        if(seater_type==0)
                        $('#room_error').append("<p style='color:red;'>* seater type required</p>");

                        if(quantity==0)
                        $('#room_error').append("<p style='color:red;'>* quantity required</p>");

                        return false;
                    }

                    return true;
                }
            });

            $('table').on('click', 'button', function(e){
               id_value = $(this).closest('tr').attr('id');
               index = parseInt(id_value[id_value.length-1]);
               console.log(index);
               delete arr[index];
               createTable(arr);
            })
        </script>
    </div>
{% endblock %}

hostelfinder/hostelAdmin/templates/hostelAdmin/hostels.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}

{% block body %}

     <div class="container" style="margin-top: 50px; text-align:right;">
       <a href="{% url 'hostelAdmin:hostel_add' %}"><button type="button" class="btn" id="addHostel"><i class="fas fa-plus"></i> Add Hostel</button></a>
     </div>

    <div class="container" style="margin-top: 20px;">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Sn</th>
                    <th>Hostel Name</th>
                    <th>Type</th>
                    <th>Contact</th>
                    <th>Location</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% for hostel in hostels %}
                 <tr>
                    <td>{{ hostel.pk}}</td>
                    <td>{{ hostel.hostel_name }}</td>
                    <td>{{ hostel.hostel_type }}</td>
                     <td>{{ hostel.hostel_phone }} </br> {{ hostel.hostel_mobile }}</td>
                       {% for l in locations %}
                            {% if hostel.location.pk == l.pk %}
                                <td>{{ l.street }}, {{ l.city }} </br> {{ hostel.additional }}</td>
                            {% endif %}
                        {% endfor %}
                    <td>
                        <a href="{% url 'hostelAdmin:hostel_details' hostel.pk %}">
                            <button type="button" class="btn btn-info"><i class="fas fa-info"></i> More Details</button>
                        </a>
                        <a href="{% url 'hostelAdmin:hostel_edit' hostel.pk %}">
                            <button type="button" class="btn btn-danger"><i class="far fa-edit"></i> Edit</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
         <ul class="pagination">
             {% if hostels.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ hostels.previous_page_number }}">Previous</a></li>
             {% endif %}
            <li class="page-item"><a class="page-link" href="#"> Page {{ hostels.number }} of {{ hostels.paginator.num_pages }}.</a></li>
            {% if hostels.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ hostels.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ hostels.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
          </ul>
    </div>
{% endblock %}

hostelfinder/hostelAdmin/templates/hostelAdmin/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HostelFinder Admin</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hostelAdmin/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>
    <body>
        <nav class="navbar navbar-expand-sm">
            <span class="navbar-brand logo" href="#">HOSTEL FINDER</span>
            <ul class="navbar-nav  ml-auto">
                <li class="nav-item">
                    <a {% block active-hostels %}class="nav-link"{% endblock %} href="{% url 'hostelAdmin:hostels' %}">Hostels</a>
                </li>
                <li class="nav-item">
                    <a {% block active-customers %}class="nav-link"{% endblock %} href="{% url 'hostelAdmin:customers' %}">Customers</a>
                </li>
            </ul>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

hostelfinder/hostelAdmin/templates/hostelAdmin/new_hostel.html
{% extends 'hostelAdmin/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}
{% load bootstrap4 %}

{% block body %}
<div class="row"></div>
    <div class="container" style="margin-top: 60px; margin-bottom: 60px; background-color:white; border-radius:4px; padding:20px; display:flex;">
        <form method="POST" class="form" enctype="multipart/form-data" action="{% url 'hostelAdmin:hostel_add' %}">
            {% csrf_token %}
            {% bootstrap_form hostel_form %}
            <hr>
            {% bootstrap_form fee_form %}
            <hr>
            {% bootstrap_form room_form %}
            <div class="form-group">
                <label style="visibility:hidden">add button</label>
                    <div class="col-sm-5">
                        <button type="button" class="btn btn-info" id="add">Add</button>
                    </div>
            </div>
            <div id="room_error"></div>
            <div id="room">
                <table class="table">
                    <thead>
                        <th>Seater Type</th>
                        <th>Quantity</th>
                        <th>Room Price</th>
                        <th>Available</th>
                    </thead>
                    <tbody id="room_table">

                    </tbody>
                </table>
            </div>
            {% bootstrap_form roomDetail_form %}
            <hr>
            {% bootstrap_form image_form %}
            <hr>
                <div class="form-group" style="clear:both; position:relative; left:45%; top:10px;">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
        </form>
       <script>
        var arr = [];

        function createJSON(seater_type,quantity,room_price,available){
            arr.push({
                "seater_type" : seater_type,
                "quantity" : quantity,
                "room_price" : room_price,
                "available" : available,
            });

            return arr;
        }

        function createTable(data){
            var room = '';
            var room_json = [];

            for(value in data){
                 room += '<tr id="room'+ value +'">';
                 room += '<td>'+data[value].seater_type+'</td>';
                 room += '<td>'+data[value].quantity+'</td>';
                 room += '<td>'+data[value].room_price+'</td>';
                 room += '<td>'+data[value].available+
                  '<button type="button" class="btn btn-danger"  style="margin-left:50px;"><i class="fas fa-trash-alt"></i></button></td>';
                 room += '</tr>';
            }

            $('#room_table').html(room);

            for(value in arr){
                room_json.push({
                    "seater_type" : arr[value].seater_type,
                    "quantity" : arr[value].quantity,
                    "room_price" : arr[value].room_price,
                    "available" : arr[value].available,
                });
            }

            $('#room_json').val(JSON.stringify(room_json));
        }

            $('#add').click(function(){

                seater_type = $('#seater_type').val();
                quantity = $('#quantity').val();
                room_price = $('#room_price').val();
                available = $('#available').val();

                if(valid()){
                    createJSON(seater_type,quantity,room_price,available);
                    console.log(arr);
                    createTable(arr);
                    $('#room_price').val("");
                }

                function valid(){
                    if(room_price == "" || seater_type == 0 || quantity == 0){
                        $('#room_error').html("<p style='color:red;'>please! insert the values.....<p>");

                        if(room_price=="")
                        $('#room_error').append("<p style='color:red;'>* room price required</p>");

                        if(seater_type==0)
                        $('#room_error').append("<p style='color:red;'>* seater type required</p>");

                        if(quantity==0)
                        $('#room_error').append("<p style='color:red;'>* quantity required</p>");

                        return false;
                    }

                    return true;
                }
            });

            /* for delete */
            $('table').on('click', 'button', function(e){
               id_value = $(this).closest('tr').attr('id');
               index = parseInt(id_value[id_value.length-1]);
               console.log(index);
               delete arr[index];
               createTable(arr);
            })
    </script>
    </div>
{% endblock %}