hostelfinder/hostelfinder/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hostelAdmin/', include('hostelAdmin.urls')),
    url(r'^hostelfinder/', include('webpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hostelfinder/webpage/urls.py
from . import views
from django.conf.urls import url

app_name = 'webpage'

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^hostels/(?P<pk>[0-9]+)/$', views.HostelDetailView, name='hostel_details'),
    url(r'^hostels/edit/(?P<pk>[0-9]+)/$', views.HostelEditView, name='hostel_edit'),
    url(r'^hostel/(?P<pk>[0-9]+)/rate/(?P<rate>[1-5]+)/$', views.rating, name='rate'),
    url(r'^register_form/(?P<user_type>[a-zA-Z_]+)/$', views.register_form_view, name='register_form'),
    url(r'^login/', views.login_form_view, name='login'),
    url(r'^logout/', views.log_out, name='logout'),
    url(r'^search_bar/', views.search_bar, name='search_bar'),
    url(r'^user_page/hostel_owner/(?P<user_id>[0-9]+)/$', views.user_hostel_owner, name='user_hostel_owner'),
    url(r'^user_page/student/(?P<user_id>[0-9]+)/$', views.user_student, name='user_student'),
]

hostelfinder/hostelAdmin/models.py
from django.db import models
from django.urls import reverse

class Location(models.Model):
    district = models.CharField(max_length=250, default="Kathmandu")
    street = models.CharField(max_length=250)
    province = models.IntegerField(default=3)
    zip = models.CharField(max_length=250, default="44600")
    country = models.CharField(max_length=250, default="Nepal")

    def __str__(self):
        return self.street + ' - ' + self.district

class Hostel(models.Model):
    HOSTEL_CHOICE = {
        ('B','Boys Hostel'),
        ('G', 'Girls Hostel'),
    }
    hostel_name =  models.CharField(max_length=250)
    hostel_type =  models.CharField(max_length=20, choices=HOSTEL_CHOICE)
    hostel_phone =  models.CharField(max_length=100, null = True, blank=True)
    hostel_mobile = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default=1)
    latitude = models.DecimalField(max_digits=10,decimal_places=8, default=0.000000)
    longitude = models.DecimalField(max_digits=11,decimal_places=8, default=0.00000)
    additional_location = models.CharField(max_length=250, null = True, blank=True)

    #def get_absolute_url(self):
     #   return reverse('hostelAdmin:hostel_details', kwargs={'pk':self.pk})

    def __str__(self):
        return str(self.pk)+' - '+self.hostel_name + '('+  self.hostel_type +')'


class Room(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    seater_type= models.IntegerField(default=1)
    quantity = models.IntegerField(default=1)
    room_price = models.CharField(max_length=250)
    available = models.IntegerField(default=0)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' - room'+  str(self.quantity)

class Fee(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    admission_fee = models.IntegerField(default=0)
    refundable_fee = models.IntegerField(default=0)
    security_fee = models.IntegerField(default=0)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' fee'

class Image(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    profile_image = models.FileField(null=True,blank=True)
    hostel_image = models.FileField(null=True,blank=True)
    kitchen = models.FileField(null=True,blank=True)
    room = models.FileField(null=True,blank=True)

    def __str__(self):
        return str(self.hostel.pk)+' : '+self.hostel.hostel_name + ' images'

hostelfinder/webpage/models.py
from django.db import models
from hostelAdmin.models import Hostel

class User(models.Model):
    USER_TYPE_CHOICE = {
        ('O','Hostel_Owner'),
        ('S', 'Student'),
    }
    first_name =  models.CharField(max_length=250)
    last_name =  models.CharField(max_length=250)
    user_name =  models.CharField(max_length=250)
    password =  models.CharField(max_length=250)
    email =  models.EmailField(max_length=250,null=True,blank=True)
    contact =  models.CharField(max_length=250,null=True,blank=True)
    user_type =  models.CharField(max_length=20, choices=USER_TYPE_CHOICE)

    def __str__(self):
        return str(self.user_name) + ' - ' + str(self.pk)

class HostelOwner(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)

class Student(models.Model):
    GENDER_CHOICE = {
        ('M', 'Male'),
        ('F', 'Female'),
    }
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    institute =  models.CharField(max_length=250)
    gender =  models.CharField(max_length=25, choices= GENDER_CHOICE)
    date_of_birth =  models.DateField(null=True,blank=True)

    def __str__(self):
        return str(self.user)

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    rating = models.IntegerField()
    avg = models.DecimalField(max_digits=20,decimal_places=1,default="0.0")

    def __str__(self):
        return str(self.user) + ' - ' + str(self.hostel) + ' - ' + str(self.rating)

    # def save(self, *args, **kwargs):
    #     hostel = Hostel.objects.get(id=self.hostel_id)
    #
    #     if Rating.objects.filter(hostel=hostel).exists():
    #         total_rating = 0
    #         rating_hostel = Rating.objects.filter(hostel=hostel)
    #         for rating in rating_hostel:
    #             total_rating = total_rating + rating.rating
    #         avg_rating = total_rating / len(rating_hostel)
    #     else:
    #         avg_rating = 0.0
    #     print(avg_rating)
    #     Rating.objects.filter(hostel=hostel).update(avg=avg_rating)
    #     self.avg = avg_rating
    #     super(Rating, self).save(*args, **kwargs)

hostelfinder/webpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.core.paginator import Paginator
from .forms import RegistrationForm, StudentForm, LogInForm, SearchForm
from hostelAdmin.models import Hostel, Room, Location, Fee, Image
from hostelAdmin.forms import HostelForm, RoomForm, FeeForm, RoomDetailForm, ImageForm
from webpage.models import User, HostelOwner, Student, Rating
import json
import math
import requests
from django.conf import settings
import os

def haversine(hostel,latitude,longitude):
    R = 6372800  # Earth radius in meters
    diff_latitude = latitude-float(hostel.latitude)
    diff_longitude = longitude-float(hostel.longitude)

    phi1, phi2 = math.radians(hostel.latitude), math.radians(latitude)
    dphi = math.radians(diff_latitude)
    dlambda = math.radians(diff_longitude)

    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2

    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    # diff_latitude = float(hostel.latitude)-latitude
    # diff_longitude = float(hostel.longitude)-longitude
    # e = math.sqrt((diff_latitude*diff_latitude) + (diff_longitude*diff_longitude))
    # print(f'{hav}-{hostel.location.street}-{hostel.hostel_name}')

def near_hostel(student_institute,similar_hostels):
    # file = os.path.join(settings.BASE_DIR, 'webpage/static/webpage/location.json')
    # json_file = open(file)
    # results = json.load(json_file)
    # json_file.close()

    #get json response from google geocoder api using url
    url = 'https://maps.googleapis.com/maps/api/geocode/json'
    institute = student_institute + ', Kathmandu'
    params = {'sensor': 'false', 'address': institute,'key':'AIzaSyDJ5YrHe6GorQ8BVPtT_gsmTM6ElhZwEHY'}
    r = requests.get(url, params=params)
    results = r.json()
    
    location  = results['results'][0]['geometry']['location']
    latitude=location['lat']
    longitude=location['lng']
    near_hostel = []

    for hostel in similar_hostels:
        e = haversine(hostel, latitude, longitude)
        if e < 1000:
            near_hostel.append([hostel,e])

    if len(near_hostel):
        near_hostel.sort(key=lambda x: x[1])
        hostel = []
        for h in near_hostel:
            hostel.append(h[0])
        return hostel[:12]
    else:
        return 0

def popular_hostel():
    rating = Rating.objects.order_by('-avg').values_list('hostel','avg').distinct()[:9]
    hostel =[]
    for rating in rating:
        hostel.append(int(rating[0]))

    avg_hostel =[]
    for h in hostel:
        avg_hostel.append(Hostel.objects.get(id=h))
    # print(avg_hostel)
    return avg_hostel

def evaluate_cosine_similarity(user,similar_user):
    numerator = 0
    user_square_sum = 0
    similar_user_square_sum = 0

    for i in range(len(user)):
        numerator = numerator + (user[i]*similar_user[i])
        user_square_sum = user_square_sum + (user[i]*user[i])
        similar_user_square_sum = similar_user_square_sum + (user[i]*user[i])

    denominator = math.sqrt(user_square_sum) + math.sqrt(similar_user_square_sum)
    similarity = numerator/denominator
    return similarity

def predict_user_item_rating(user,similar_user,cosine_similarity):
    denominator = 0
    predictate_rating = []

    similar_user_average = []
    user_average = 0

    for i in range(len(cosine_similarity)):
        denominator = denominator + cosine_similarity[i]

    for i in range(len(similar_user)):
        average = 0;
        total = 0;
        for j in range(len(similar_user[0])):
            total = total + similar_user[i][j]
        average = total/len(similar_user[0])
        similar_user_average.append(average)

    total = 0
    for i in range(len(user)):
        total = total + user[i]
    user_average  = total/len(user)

    for j in range(len(similar_user[0])):
        numerator = 0
        for i in range(len(similar_user)):
            numerator = numerator + ((similar_user[i][j]-similar_user_average[i])*cosine_similarity[i])
        predict = user_average + (numerator/denominator)
        predictate_rating.append(predict)

    return predictate_rating

def similar_hostel(user_id):
    user_rated_hostel = []
    similar_rating_user_id = []
    similar_user_rated_hostels = []
    student = Student.objects.get(user_id=user_id)
    rating = Rating.objects.filter(user=student.user_id)

    if student.gender == 'M':
        hostel_type = 'B'
    else:
        hostel_type = 'G'

    #get the hostels rated by active user
    for rating in rating:
        user_rated_hostel.append(rating.hostel)

    #get the similar users who rated the hostels rated by active user
    similar_rating = Rating.objects.filter(hostel__in=user_rated_hostel,user__student__gender=student.gender).order_by('user_id').exclude(user_id=user_id)

    #prepare the list of similar rating users and the hostels they rated
    for s in similar_rating:
        similar_rating_user_id.append(s.user_id)

        for h in Rating.objects.filter(user_id=s.user_id,hostel__hostel_type='B'):
            similar_user_rated_hostels.append(h.hostel_id)

    hostel = []

    if similar_user_rated_hostels and similar_rating_user_id:
        # removing duplicates
        similar_rating_user_id = list(dict.fromkeys(similar_rating_user_id))
        similar_user_rated_hostels = list(dict.fromkeys(similar_user_rated_hostels))
        similar_rating_user_id.sort()
        similar_user_rated_hostels.sort()

        #create user-item matrix for both active user and similar users
        similar_user =  [[0] * len(similar_user_rated_hostels) for i in range(len(similar_rating_user_id))]
        user = []

        for i,similar_user_id in enumerate(similar_rating_user_id):
            for j,hostel_id in enumerate(similar_user_rated_hostels):
                if Rating.objects.filter(user_id=similar_user_id,hostel_id=hostel_id).exists():
                    r = Rating.objects.values('rating').get(user_id=similar_user_id,hostel_id=hostel_id)
                    rate = r['rating']
                else:
                   rate = 0
                similar_user[i][j] = rate


        for i, similar_user_id in enumerate(similar_rating_user_id):
            for j, hostel_id in enumerate(similar_user_rated_hostels):
                print(str(similar_user_id)+'-'+str(hostel_id)+"="+str(similar_user[i][j]))
            print()

        for j in similar_user_rated_hostels:
            if Rating.objects.filter(user_id=user_id, hostel_id=j).exists():
                r = Rating.objects.values('rating').get(user_id=user_id, hostel_id=j)
                rate = r['rating']
            else:
                rate = 0
            user.append(rate)

        print(user)

        #calculating similarity through cosine similarity
        cosine_similarity = []


        print("cosine similarity:")
        for i in range(len(similar_rating_user_id)):
            similarity = evaluate_cosine_similarity(user,similar_user[i])
            cosine_similarity.append(similarity)
            print(str(similar_rating_user_id[i])+'-'+str(round(similarity,3)))

        if cosine_similarity:
            #predicting the rating for the each item of active user
            predictate_rating = predict_user_item_rating(user,similar_user,cosine_similarity)

            print("predictate rating:")
            for i in range(len(similar_user_rated_hostels)):
                print((str(similar_user_rated_hostels[i])+'-'+str(round(predictate_rating[i],2))))

            #now finding the top predictate hostel rating
            predictate_similar_hostel = []
            hostels = []
            for j, hostel_id in enumerate(similar_user_rated_hostels):
                predictate_similar_hostel.append((hostel_id,predictate_rating[j]))
            predictate_similar_hostel.sort(key=lambda x  : x[1],reverse=True)

            print("ranked hostels")
            for p in predictate_similar_hostel:
                hostels.append(p[0])
                print(p[0])

            for h in hostels:
                hostel.append( Hostel.objects.get(id=h))

        # for h in hostel:
        #     print(h)

    return hostel[:9]

def log_in_session(request):
    if 'user_id' in request.session:
        user = get_object_or_404(User,id = request.session['user_id'])

        if user.user_type=='O':
            return redirect("webpage:user_hostel_owner",user.id)
        else:
            return redirect("webpage:user_student",user.id)

def log_out(request):
    if request.session.has_key('user_id'):
        request.session.flush()
        return redirect("webpage:homepage")

def search_bar(request):
    search_value = request.GET.get('search_value')
    print(search_value)

    searched= False
    hostel = Hostel.objects.all()

    if search_value:
        hostel = hostel.filter(hostel_name__icontains=search_value)
        searched = True

    if searched:
        paginator = Paginator(hostel, 18)  # Show 18 contacts per page
        page = request.GET.get('page')
        hostels = paginator.get_page(page)

        if 'user_id' in request.session:
            user_id = request.session['user_id']
            user = get_object_or_404(User, id=user_id)
            return render(request, 'webpage/search_result.html', {'hostels': hostels, 'username': user.user_name})
        else:
            return render(request, 'webpage/search_result.html', {'hostels': hostels})

    else:
        return redirect("webpage:homepage")

def homepage(request):
    if 'user_id' in request.session:
        return log_in_session(request)


    if request.method=="GET":
        search_form = SearchForm(request.GET)
        district = request.GET.get('district')
        street = request.GET.get('street')
        hostel_type =request.GET.get('hostel_type')
        seater_type = request.GET.get('seater_type')
        quantity = request.GET.get('quantity')
        price_range1 =request.GET.get('price_range1')

hostelfinder/webpage/templates/webpage/hostel_detail.html
<style>
    .carousel{
        height: 250px !important;
    }
    /* Make the image fully responsive */
    .carousel-inner img {
        width:100%;
        height:100%;
        object-fit: cover;
    }
    .text-block {
        background-color: green;
        color: white;
        opacity:0.5;
        text-align:center;
        font-weight: bold;
        position:absolute;
        width:100%;
        top: 78%;
    }
    .infobox{
        background-color: #FFA500FF;
        opacity: 0.7;
        color:white;
        font-weight:bolder;
        padding:10px;
    }
    .hostel-name{
        background-color: green;
        opacity:0.8;
        color: white;
        text-align: center;
        text-transform: uppercase;
        font-weight:bold;
        font-size:25px;
    }
    .room-available{
        background-color: green;
        opacity:0.8;
        color: white;
        text-align: center;
        margin-top: 10px;
        font-size:25px;
    }
    td{
        vertical-align: top;
    }
    .profile-img-box{
        padding-left: 0 !important;
        padding-right: 0 !important;
        margin-right: 0 !important;
        height:200px;
        width:100%;
        border:6px solid #FFA500A6;
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
        object-fit: cover;
    }
    iframe{
        padding-left:0 !important;
        padding-right:0 !important;
    }
    .hotel-rating .fa-star{color: white;}
    .hotel-rating .rated{color: orange;}
    .your-hotel-rating .fa-star{color: black;}
    .your-hotel-rating .rated{color: orange;}
</style>
{% extends 'webpage/nav.html' %}
{% load static %}
{% block head %}
{% endblock %}
{% block body %}
<div class="container-fluid top-ban">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="col-sm-12 row" style="margin: 0 !important; padding:0 !important;">
                <iframe class="col-sm-7" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q={{hostel.latitude}},{{hostel.longitude}} (custom heading)&amp;output=embed" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                {% with image=hostel.image_set.first %}
                    {% if image.profile_image %}
                        <img class="col-sm-5 profile-img-box" src="{{ image.profile_image.url }}" alt="profile image">
                    {% endif %}
                {% endwith %}
                <div class="hotel-rating" style="position:absolute; bottom:10px; right:10px;">
                    {% with rating=hostel.rating_set.first %}
                        {% for i in '12345' %}
                            {% if forloop.counter <= rating.avg %}
                                <span class="fa fa-star rated" data-rating="{{ forloop.counter }}"></span>
                            {% else %}
                                <span class="fa fa-star" data-rating="{{ forloop.counter }}"></span>
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                </div>
            </div>
            <div class="infobox">
                 <table class="table-sm">
                      <tbody style="color:white;">
                        <tr>
                          <td>Hostel Type : </td>
                          <td>{{ hostel.get_hostel_type_display }}</td>
                        </tr>
                        <tr>
                          <td>Contact No : </td>
                          <td>{{ hostel.hostel_phone }}, {{ hostel.hostel_mobile }}</td>
                        </tr>
                        <tr>
                          <td>Location &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: </td>
                          <td>
                              {{ hostel.location.district }}, {{ hostel.location.street }}
                              {% if hostel.additional_location %}
                                    <br>{{ hostel.additional_location }}
                              {% endif %}
                          </td>
                        </tr>
                      </tbody>
                    </table>
            </div>
             <div class="col-sm-12">
                    <table class="table table-striped">
                        <tbody>
                        {% with fee=hostel.fee_set.first %}
                            <tr>
                                <th scope="row">Admission Fee :</th>
                                <td>{{ fee.admission_fee }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Refundable Fee :</th>
                                <td>{{ fee.refundable_fee }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Security Fee :</th>
                                <td>{{ fee.security_fee }}</td>
                            </tr>
                        {% endwith %}
                        </tbody>
                    </table>
             </div>
            {% if username %}
            <div class="row col-sm-12">
                <div class="col-sm-6 your-hotel-rating">
                {% if rating_user or username %}
                    <h6>Your Rating: </h6>
                    {% for i in '12345' %}
                        {% if forloop.counter <= rating_user %}
                            <a href="{% url 'webpage:rate' hostel.pk forloop.counter %}" ><span class="fa fa-star rated" data-rating="{{ forloop.counter }}"></span></a>
                        {% else %}
                            <a href="{% url 'webpage:rate' hostel.pk forloop.counter %}" ><span class="fa fa-star" data-rating="{{ forloop.counter }}"></span></a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </div>
                <div class="col-sm-6">
                    {% if hostel_owner %}
                        <a href="{% url 'webpage:hostel_edit' hostel.pk %}" style="position:absolute;right:0;bottom:0;">
                            <button type="button" class="btn btn-info"><i class="far fa-edit"></i>Edit Details</button>
                        </a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div> <!--col-sm-4 ends here -->

        <!-- col-sm-7 starts-->
        <div class="col-sm-12 col-md-8">
            <p class="hostel-name">{{ hostel.hostel_name }}</p>
            <div id="demo" class="carousel slide" data-ride="carousel">
                  <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                  </ul>
                {% with image=hostel.image_set.first %}
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="text-block">
                            <p>Hostel</p>
                        </div>
                        <img src="{% if image.profile_image %}{{ image.profile_image.url }}{% endif %}" alt="Hostel">
                    </div>
                    <div class="carousel-item">
                        <div class="text-block">
                            <p>Kitchen</p>
                        </div>
                        <img src="{% if image.kitchen %}{{image.kitchen.url}}{% endif %}" alt="kitchen" >
                    </div>
                    <div class="carousel-item">
                        <div class="text-block">
                            <p>Bedroom</p>
                        </div>
                        <img src="{% if image.room %}{{ image.room.url }}{% endif %}" alt="bedroom" >
                    </div>
                  </div>
                {% endwith %}
                  <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                  </a>
                  <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                  </a>
            </div> <!-- Image couseral end here -->
            <p class="room-available">Room Available</p>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Seater</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Price</th>
                                <th scope="col">Available</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for room in hostel.room_set.all %}
                            <tr>
                                <td>{{ room.seater_type }}</td>
                                <td>{{ room.quantity }}</td>
                                <td>{{ room.room_price }}</td>
                                <td>{{ room.available }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- col-sm-7 ends-->
    </div>
</div>
{% endblock %}

hostelfinder/webpage/templates/webpage/login_form.html
{% extends 'webpage/nav.html' %}
{% block active-hostels %}class="nav-link active"{% endblock %}
{% load static %}
{% load bootstrap4 %}

{% block head %}
    <style>
        .container{
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .student label{
            font-size: 1.2em;
        }
        .student input, select{
            width: 100% !important;
        }
        .info{
            background: url('{% static 'webpage/images/texture.jpg' %}');
            background-size: cover;
            text-align: center;
            margin-bottom:10px;
        }

        .info p{
            font-size: 5em;
            color: white;
            text-align:center;
            text-transform: uppercase;
        }

        .info i{
            font-size: 8em;
            color: white;
            text-align: center;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container top-ban">
        <div class="row ">
            <div class="col-sm-12 col-md-7 col-lg-8 info">
                <p>Choose</p>
                <i class="fas fa-home"></i>
                <p>Your Stay</p>
            </div>
            <div class="col-sm-12 col-md-5 col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <legend>
                            <center>
                                <h4>Log In</h4>
                            </center>
                        </legend>
                    </div>
                    <div class="card-body">
                        <form class="student" action="{% url 'webpage:login' %}" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <div class="form-group">
                                <center><button type="submit" class="btn btn-danger">Submit</button></center>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hostelfinder/webpage/templates/webpage/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HostelFinder</title>
    {% load staticfiles %}
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'webpage/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>
    <body>
        <nav class="navbar navbar-expand-sm">
            <div>
                <span class="navbar-brand logo">HOSTEL FINDER</span>
            </div>
            <div class="logger">

                <form class="search-bar-form"  method="GET" action="{% url 'webpage:search_bar'%}" onsubmit="return validate_search_bar();" autocomplete="off">
                    {% csrf_token %}
                    <div class="searchbar"">
                        <input class="search_input" type="text" name="search_value" id="search_value" placeholder="Search...">
                        <input type="submit" hidden="hidden" id="submit_search">
                        <a href="#" class="search_icon" id="search_icon"><i class="fas fa-search"></i></a>
                    </div>
                    <script>
                        function validate_search_bar(){
                            var search = document.getElementById("search_value").value;

                            if(search==""){
                                alert("please enter the text to search");
                                return false;
                            }

                            return true;
                        }


                        var search_icon = document.getElementById("search_icon");

                        search_icon.addEventListener('click',function(){
                            document.getElementById("submit_search").click();
                        });
                    </script>
                </form>

                {% if username %}
                <span style="position:relative;top:3px;">Welcome {{username}}</span>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'webpage:logout' %}" style="font-weight:bold;">Log Out</a>
                {% else %}
                    <a href="{% url 'webpage:register' %}" style="font-style:italic; font-size:0.9em;">register</a> &nbsp;|&nbsp;
                    <a href="{% url 'webpage:login' %}" style="font-weight:bold;">Log In</a>
                {% endif %}
            </div>
        </nav>
        {% block body %}
        {% endblock %}

        {% include 'webpage/foot_ban.html' %}
    </body>
    <script>
        $( ".logo" ).click(function() {
            window.location.href="{% url 'webpage:homepage' %}";
        });
    </script>
</html>

hostelfinder/webpage/templates/webpage/user_page.html
{% extends 'webpage/nav.html' %}
{% load static %}
{% block body %}
<p>welcome {{end_user.user_name}}</p>
{% endblock %}